export const es =  {
  	"$ngx_new": "Nuevo",
	"$ngx_app": "Safe conductor",
	"$ngx_app_driver":"Safe conductor",
	"$ngx_dni": "DNI",
	"$ngx_certificate": "Certificado",
	"$ngx_license": "Licencia",
	"$ngx_the_license": "La licencia",
	"$ngx_ok": "Ok",
	"$ngx_year": "Año",
	"$ngx_image_of": "Imagen del ",
	"$ngx_car": "Vehiculo",
	"$ngx_register_vehicle": "Registro de vehículo",
	"$ngx_new_safe": "Eres nuevo en safe?",
	"$ngx_join_now": "Unete Ahora",
	"$ngx_address": "Dirección de habitación",
	"$ngx_address_help": "Referencia de habitación",
	"$ngx_driver": "Conductor",
	"$ngx_register": "Registrar",
	"$ngx_connect": "Conectado",
	"$ngx_unconnect": "Desconectado",
	"$ngx_yes": "Si",
	"$ngx_not": "No",
	"$ngx_error": "Error",
	"$ngx_alect": "Alerta",
	"$ngx_detail": "Detalle",
	"$ngx_data_personal": "Datos Personales",
	"$ngx_notification": "Notificación",
	"$ngx_information": "Información",
	"$ngx_save": "Guardar",
	"$ngx_cancel": "Cancelar",
	"$ngx_update": "Actualizar",
	"$ngx_profile": "Perfil",
	"$ngx_contact": "Contactos",
	"$ngx_max_contacts": "Maximo de contactos",
	"$ngx_origin": "Origen",
	"$ngx_run_date": "Fecha de Ejecución",
	"$ngx_hour_start": "Hora de inicio",
	"$ngx_hour_end": "Hora Final",
	"$ngx_amount": "Costo",
	"$ngx_destination": "Destino",
	"$ngx_status": "Estado",
	"$ngx_message": "Mensaje",
	"$ngx_reload": "Recargar",
	"$ngx_user_name": "Nombre de usuario",
	"$ngx_email": "Correo ó nombre de usuario",
	"$ngx_password": "Contraseña",
	"$ngx_re_password": "Repetir contraseña",
	"$ngx_enter": "Iniciar sesión",
	"$ngx_check_in": "Registrarse",
	"$ngx_facebook": "Facebook",
	"$ngx_google": "Google",
	"$ngx_name": "Nombres",
	"$ngx_phone": "Teléfono",
	"$ngx_add_phone": "Agregar Teléfono",
	"$ngx_user_customer": "Pasajero",
	"$ngx_user_driver": "Conductor",
	"$ngx_lastname": "Apellidos",
	"$ngx_gender": "Genero",
	"$ngx_tradermark": "Marca",
	"$ngx_enrollment": "Placa",
	"$ngx_model": "Modelo",
	"$ngx_plate": "Plate",
	"$ngx_color": "Color",
	"$ngx_serial_engine": "Serial de motor",
	"$ngx_air_conditioner": "Aire acondicionado",
	"$ngx_baby_chair": "Silla para el bebe",
	"$ngx_bodywork_serial": "Serial de carroceria",
	"$ngx_birthdate": "Fecha de nacimiento",
	"$ngx_services": "Servicios",
	"$ngx_hola": "hola",
	"$ngx_bienvenido": "Bienvenido",
	"$ngx_welcome_to": "Bienvenido a",
	"$ngx_total_available": "Total disponible",
	"$ngx_card_debit": "Tarjeta de debito",
	"$ngx_card_credit": "Tarjeta de credito",
	"$ngx_menu_new_service": "Nuevo servicio",
	"$ngx_menu_services": "Historial de rutas",
	"$ngx_menu_place": "Ubicaciónes guardadas",
	"$ngx_menu_wallet": "Monedero Safe",
	"$ngx_menu_payment": "Metodo de pago",
	"$ngx_menu_panic_button": "Boton de panico",
	"$ngx_menu_map_option": "Opciones de mapa",
	"$ngx_menu_promotion": "Promociones",
	"$ngx_menu_video_surveillance": "Video vigilancia",
	"$ngx_logout": "Cerrar Sesión",
	"$ngx_msg_error_internet": "Tienes problema con la conección a internet intentelo mas tarde",
	"$ngx_msg_error_login_facebook": "Error en el login con facebook",
	"$ngx_msg_new_service": "Desea solicitar un nuevo servicio",
	"$ngx_msg_error_server": "Algun problema con el servidor safe por favor intentelo mas tarde.",
	"$ngx_msg_update_sucessfull": "Actualizado exitosamente",
	"$ngx_msg_err_img_certificate": "Se registro el vehiculo pero fallo al guardar la imagen del certificado intente mas tarde",
	"$ngx_msg_err_img_vehicle":"Se registro el vehiculo pero fallo al guardar las imagenes del vehiculo intente mas tarde",
	"$ngx_msg_option_map_changed_waze": "Cambiado a Waze",
	"$ngx_msg_option_map_changed_google_map": "Cambiado a GoogleMap",
	"$ngx_your_email": "Tu correo electrónico",
	"$ngx_your_password": "Tu contraseña",
	"$ngx_your_phone": "Tu teléfono",
	"$ngx_your_name": "Tus nombres",
	"$ngx_your_lastname": "Tus apellidos",
	"$ngx_your_dni": "Tu DNI",
	"$ngx_your_gender": "Tu genero",
	"$ngx_your_tradermark": "Tu Marca",
	"$ngx_your_birthdate": "Tu fecha de nacimiento",
	"$ngx_your_address": "Tu dirección de habitación",
	"$ngx_your_address_help": "Tu referencia de habitación.",
	"$ngx_where_do_you_want_to_go": "¿A dónde quieres ir?",
	"$ngx_change_your_locate": "Fija tu ubicación en el mapa",
	"$ngx_reload_map": "Recargar el mapa",
	"$ngx_enter_valid_email": "* Ingrese un correo ó nombre de usuario válido",
	"$ngx_enter_valid_name": "* Solo nombres sin caracteres especiales.",
	"$ngx_enter_valid_user_name": "* Sin caracteres especiales.",
	"$ngx_enter_valid_lastname": "* Solo apellidos sin caracteres especiales.",
	"$ngx_enter_valid_phone": "* Mas de 6 digitos.",
	"$ngx_enter_valid_dni": "* Solo numero",
	"$ngx_password_more_6_characters": "Su contraseña debe tener más de 6 caracteres.",
	"$ngx_incorrect_password_confirmation": "Confirmación de contraseña incorrecta",
	"$ngx_incorrect_gender_confirmation": "Seleccione un genero",
	"$ngx_incorrect_country_confirmation": "Seleccione un codigo de pais",
	"$ngx_cordova_not_available": "La plataforma no esta disponible por favor ejecutar en otra plataforma",
	"$ngx_url_image_logo": "assets/imgs/logo_safe.png",
	"$ngx_url_background_safe": "assets/imgs/fondo_safe.png",
	"$ngx_url_avatar_default": "assets/imgs/camera.png",
	"$ngx_genders": [{id: 1,name: "Masculino"} , {id: 2,name: "Femenino"}],
	"$ngx_code_country": [{"code": "+54","country": "Argentina"} , {"code": "+297","country": "Aruba"} , {"code": "+1","country": "Canada"} , {"code": "+56","country": "Chile"} , {"code": "+57","country": "Colombia"} , {"code": "+58","country": "Venezuela"} , {"code": "+506","country": "Costa Rica"} , {"code": "+599","country": "Curacao"} , {"code": "+593","country": "Ecuador"} , {"code": "+34","country": "España"} , {"code": "+502","country": "Guatemala"} , {"code": "+507","country": "Panama"} , {"code": "+51","country": "Peru"} , {"code": "+1","country": "Republica Dominicana"} , {"code": "+46","country": "Suecia"}],
	"$ngx_code": "Codigo",
	"$ngx_country": "Pais",
	"$ngx_code400": "La solicitud contiene sintaxis errónea y no debería repetirse",
	"$ngx_code401": "El usuario es incorrecto  intentelo nuevamente",
	"$ngx_code404": "Recurso no encontrado.",
	"$ngx_code201": "Se ha registrado exitosamente.",
	"$ngx_code2011": "Se ha actualizado exitosamente.",
	"$ngx_code422": "No puede procesar la solicitud.",
	"0000001": "Registro creado exitosamente",
    "0000002": "Falta parametros en la petición",
    "0000003": "Registro actualizado exitosamente",
    "0000004": "Registro eliminado exitosamente",
    "0000005": "El correo ya esta registrado en safe.",
    "0000006": "Intente mas tarde.",
    "0000007": "Correo o contraseña incorrecta",
    "0000008": "Autenticada exitosamente",
    "0000009": "Ya existe una cuenta registrada como conductor",
    "0000010": "Ya existe una cuenta registrada como pasajero",
    "0000011": "El dni ya se encuentra registrado",
    "0000012": "La placa del vehiculo ya esta registrada",
    "0000013": "El correo no esta registrado en safe.",
    "0000014": "El codigo de verificacion ya fue enviado a ",
    "0000015": "El codigo de verificacion no es correcto",
    "0000016": "La contraseña fue cambiada exitosamente",
    "0000017": "Codigo invalido",
    "0000018": "Usuario fue cancelado no possees los permisos necesarios de acceso a tu cuenta facebook.",
    "0000019": "Ya se envio un codigo a tu correo espere 5 mimito",
    "0000020": "Estas en modo de desarrollo usa usuario de prueba de facebook cierra sesión en tu applicacion de facebook y intenta de nuevo",
    "0000021": "El nombre de usuario ya esta registrado en safe",
	"$ngx_res_color":["Rojo", "Azul", "Blanco", "Negro", "Amarillo", "Verde", "Rosado", "Morado", "Gris"]
};