export const es =  {
"$ngx_new": "Nuevo",
"$ngx_app": "Controlador seguro",
"$ngx_app_driver": "Controlador seguro",
"$ngx_dni": "DNI",
"$ngx_certificate": "Certificado",
"$ngx_license": "Licencia",
"$ngx_the_license": "La licencia",
"$ngx_ok": "Ok",
"$ngx_year": "Año",
"$ngx_image_of": "Imagen de la",
"$ngx_car": "Vehículo",
"$ngx_register_vehicle": "Registro del vehículo",
"$ngx_new_safe": "¿Eres nuevo en Safe?",
"$ngx_join_now": "Únete ahora",
"$ngx_address": "Dirección de la habitación",
"$ngx_address_help": "Referencia de habitación",
"$ngx_driver": "Driver",
"$ngx_register": "Registrarse",
"$ngx_connect": "Conectado",
"$ngx_unconnect": "Desconectado",
"$ngx_yes": "Sí",
"$ngx_not": "No",
"$ngx_error": "Error",
"$ngx_alect": "Alerta",
"$ngx_detail": "Detalle",
"$ngx_data_personal": "Datos personales",
"$ngx_notification": "Notificación",
"$ngx_information": "Información",
"$ngx_save": "Guardar",
"$ngx_cancel": "Cancelar",
"$ngx_update": "Actualizar",
"$ngx_profile": "Perfil",
"$ngx_contact": "Contactos",
"$ngx_max_contacts": "Número máximo de contactos",
"$ngx_origin": "Origen",
"$ngx_run_date": "Fecha de ejecución",
"$ngx_hour_start": "Hora de inicio",
"$ngx_hour_end": "Hora de finalización",
"$ngx_amount": "Costo",
"$ngx_destination": "Destino",
"$ngx_status": "Estado",
"$ngx_message": "Mensaje",
"$ngx_reload": "Reload",
"$ngx_user_name": "Nombre de usuario",
"$ngx_email": "Correo o nombre de usuario",
"$ngx_password": "Contraseña",
"$ngx_re_password": "Repetir contraseña",
"$ngx_enter": "Iniciar sesión",
"$ngx_check_in": "Registrarse",
"$ngx_facebook": "Facebook",
"$ngx_google": "Google",
"$ngx_name": "Nombres",
"$ngx_phone": "Teléfono",
"$ngx_add_phone": "Agregar teléfono",
"$ngx_user_customer": "Pasajero",
"$ngx_user_driver": "Driver",
"$ngx_lastname": "Apellido",
"$ngx_gender": "Género",
"$ngx_tradermark": "Marca",
"$ngx_enrollment": "Placa",
"$ngx_model": "Modelo",
"$ngx_plate": "Placa",
"$ngx_color": "Color",
"$ngx_serial_engine": "Motor serial",
"$ngx_air_conditioner": "Aire acondicionado",
"$ngx_baby_chair": "Silla para el bebé",
"$ngx_bodywork_serial": "Body serial",
"$ngx_birthdate": "Fecha de nacimiento",
"$ngx_services": "Servicios",
"$ngx_hola": "hola",
"$ngx_welcome": "Bienvenido",
"$ngx_welcome_to": "Bienvenido a",
"$ngx_total_available": "Total disponible",
"$ngx_card_debit": "Tarjeta de débito",
"$ngx_card_credit": "Tarjeta de crédito",
"$ngx_menu_new_service": "Nuevo servicio",
"$ngx_menu_services": "Historial de rutas",
"$ngx_menu_place": "Ubicaciones guardadas",
"$ngx_menu_wallet": "Monedero seguro",
"$ngx_menu_payment": "Método de pago",
"$ngx_menu_panic_button": "Botón de pánico",
"$ngx_menu_map_option": "Opciones de mapa",
"$ngx_menu_promotion": "Promociones",
"$ngx_menu_video_surveillance": "Videovigilancia",
"$ngx_logout": "Cerrar sesión",
"$ngx_msg_error_internet": "Tiene un problema con la conexión a Internet, inténtelo más tarde",
"$ngx_msg_error_login_facebook": "Error al iniciar sesión con facebook",
"$ngx_msg_new_service": "Desea solicitar un nuevo servicio",
"$ngx_msg_error_server": "Algún problema con el servidor seguro, inténtelo de nuevo más tarde.",
"$ngx_msg_update_sucessfull": "Actualización exitosa",
"$ngx_msg_err_img_certificate": "El vehículo se registró pero no se pudo guardar la imagen del certificado. Inténtelo más tarde",
"$ngx_msg_err_img_vehicle": "El vehículo fue registrado pero no pudo guardar las imágenes del vehículo. Inténtelo más tarde",
"$ngx_msg_option_map_changed_waze": "Changed to Waze",
"$ngx_msg_option_map_changed_google_map": "Cambiado a GoogleMap",
"$ngx_your_email": "Tu correo electrónico",
"$ngx_your_password": "Tu contraseña",
"$ngx_your_phone": "Su teléfono",
"$ngx_your_name": "Tus nombres",
"$ngx_your_lastname": "Tus apellidos",
"$ngx_your_dni": "Tu ID",
"$ngx_your_gender": "Tu género",
"$ngx_your_tradermark": "Tu marca",
"$ngx_your_birthdate": "Tu fecha de nacimiento",
"$ngx_your_address": "La dirección de su habitación",
"$ngx_your_address_help": "Referencia de su habitación.",
"$ngx_where_do_you_want_to_go": "¿A dónde quieres ir?",
"$ngx_change_your_locate": "Establezca su ubicación en el mapa",
"$ngx_reload_map": "Recargar el mapa",
"$ngx_enter_valid_email_user_name": "* Ingrese un correo electrónico o nombre de usuario válido",
"$ngx_enter_valid_email": "* Ingrese un correo electrónico",
"$ngx_enter_valid_name": "* Solo nombres sin caracteres especiales.",
"$ngx_enter_valid_user_name": "* No hay caracteres especiales.",
"$ngx_enter_valid_lastname": "* Solo apellidos sin caracteres especiales.",
"$ngx_enter_valid_phone": "* Más de 6 dígitos.",
"$ngx_enter_valid_dni": "* Only number",
"$ngx_password_more_6_characters": "Su contraseña debe tener más de 6 caracteres.",
"$ngx_incorrect_password_confirmation": "Confirmación de contraseña incorrecta",
"$ngx_incorrect_gender_confirmation": "Seleccione un género",
"$ngx_incorrect_country_confirmation": "Seleccione un código de país",
"$ngx_cordova_not_available": "La plataforma no está disponible, ejecútela en otra plataforma",
"$ngx_url_image_logo": "asset/imgs/logo_safe.png",
"$ngx_url_background_safe": "asset/imgs/fondo_safe.png",
"$ngx_url_avatar_default": "asset/imgs/camera.png",
"$ngx_genders": [{id: 1, name: "Male"}, {id: 2, name: "Feminine"}],
"$ngx_code_country": [{"code": "+54", "country": "Argentina"}, {"code": "+297", "country": "Aruba"}, {"code": " +1 "," país ":" Canadá "}, {" código ":" +56 "," país ":" Chile "}, {" código ":" +57 "," país ":" Colombia "} , {"código": "+58", "país": "Venezuela"}, {"código": "+506", "país": "Costa Rica"}, {"código": "+599", "país": "Curazao"}, {"código": "+593", "país": "Ecuador"}, {"código": "+34", "país": "España"}, {"código ":" +502 "," país ":" Guatemala "}, {" código ":" +507 "," país ":" Panamá "}, {" código ":" +51 "," país ":" Perú "}, {" código ":" +1 "," país ":" República Dominicana "}, {" código ":" +46 "," país ":" Suecia "}],
"$ngx_code": "Código",
"$ngx_country": "País",
"$ngx_code400": "La solicitud contiene una sintaxis incorrecta y no debe repetirse",
"$ngx_code401": "El usuario está equivocado, inténtalo de nuevo",
"$ngx_code404": "Recurso no encontrado.",
"$ngx_code201": "Se ha registrado correctamente.",
"$ngx_code2011": "Actualización exitosa.",
"$ngx_code422": "No puede procesar la solicitud.",
"0000001": "Registro creado con éxito",
"0000002": "Faltan parámetros en la solicitud",
"0000003": "Registro actualizado correctamente",
"0000004": "Registro eliminado exitosamente",
"0000005": "El correo electrónico ya está registrado en una caja fuerte",
"0000006": "Inténtalo más tarde",
"0000007": "Correo electrónico o contraseña incorrectos",
"0000008": "Autenticado correctamente",
"0000009": "Ya existe una cuenta registrada como controlador",
"0000010": "Ya existe una cuenta registrada como pasajero",
"0000011": "El IDN ya está registrado",
"0000012": "La matrícula del vehículo ya está registrada",
"0000013": "El correo electrónico no está registrado en una caja fuerte",
"0000014": "El código de verificación ya se ha enviado a",
"0000015": "El código de verificación no es correcto",
"0000016": "La contraseña se cambió con éxito",
"0000017": "Código no válido",
"0000018": "El usuario fue cancelado y no posee los permisos de acceso necesarios a su cuenta de Facebook",
"0000019": "Ya envié un código a su correo, espere 5 mimito",
"0000020": "Estás en modo de desarrollo, usa el usuario de prueba de Facebook para cerrar sesión en tu aplicación de Facebook y vuelve a intentarlo",
"0000021": "El nombre de usuario ya está registrado en una caja fuerte",
"0000022": "Falló la capa de validación",
"$ngx_res_color": ["Rojo", "Azul", "Blanco", "Negro", "Amarillo", "Verde", "Rosa", "Púrpura", "Gris"]
};